<script type="text/javascript">
<!--
document.write('<span id="translate" style="display:block;text-align:left;padding-bottom:5px;padding-top:21px;">Translate</span>' +
'<span id="flags" class="flags">' + '<a target="_parent" title="Francais"  href="http://www.google.com/translate?hl=en&amp;ie=UTF8&amp;langpair=en%7Cfr&amp;u=http://{php}echo $_SERVER["SERVER_NAME"] . $_SERVER["REQUEST_URI"]; {/php}"><img class="translate" src="/forms/assets/flag_fr.gif" alt="Francais" title="Francais"  /></a>' +
'<a target="_parent" title="Deutsch"  href="http://www.google.com/translate?hl=en&amp;ie=UTF8&amp;langpair=en%7Cde&amp;u=http://{php}echo $_SERVER["SERVER_NAME"] . $_SERVER["REQUEST_URI"]; {/php}"><img class="translate" src="/forms/assets/flag_de.gif" alt="Deutsch" title="Deutsch"  /></a>' +
'<a target="_parent" title="Espanol"  href="http://www.google.com/translate?hl=en&amp;ie=UTF8&amp;langpair=en%7Ces&amp;u=http://{php}echo $_SERVER["SERVER_NAME"] . $_SERVER["REQUEST_URI"]; {/php}"><img class="translate" src="/forms/assets/flag_es.gif" alt="Espanol" title="Espanol"  /></a>' +
'<a target="_parent" title="Italiano"  href="http://www.google.com/translate?hl=en&amp;ie=UTF8&amp;langpair=en%7Cit&amp;u=http://{php}echo $_SERVER["SERVER_NAME"] . $_SERVER["REQUEST_URI"]; {/php}"><img class="translate" src="/forms/assets/flag_it.gif" alt="Italiano" title="Italiano"  /></a>' +
'<a target="_parent" title="Portugese"  href="http://www.google.com/translate?hl=en&amp;ie=UTF8&amp;langpair=en%7Cpt&amp;u=http://{php}echo $_SERVER["SERVER_NAME"] . $_SERVER["REQUEST_URI"]; {/php}"><img class="translate" src="/forms/assets/flag_pt.gif" alt="Portugese" title="Portugese"  /></a>' +
'<a target="_parent" title="Japanese"  href="http://www.google.com/translate?hl=en&amp;ie=UTF8&amp;langpair=en%7Cja&amp;u=http://{php}echo $_SERVER["SERVER_NAME"] . $_SERVER["REQUEST_URI"]; {/php}"><img class="translate" src="/forms/assets/flag_ja.gif" alt="Japanese" title="Japanese"  /></a>' +
'<a target="_parent" title="Korean"  href="http://www.google.com/translate?hl=en&amp;ie=UTF8&amp;langpair=en%7Cko&amp;u=http://{php}echo $_SERVER["SERVER_NAME"] . $_SERVER["REQUEST_URI"]; {/php}"><img class="translate" src="/forms/assets/flag_ko.gif" alt="Korean" title="Korean"  /></a>' +
'<a target="_parent" title="Chinese"  href="http://www.google.com/translate?hl=en&amp;ie=UTF8&amp;langpair=en%7Czh-CN&amp;u=http://{php}echo $_SERVER["SERVER_NAME"] . $_SERVER["REQUEST_URI"]; {/php}"><img class="translate" src="/forms/assets/flag_zh-CN.gif" alt="Chinese" title="Chinese"  /></a>' +
'</span>')
--> </script>
<noscript></noscript>